name: "Install Poetry"
author: "Marcel Arns <marcel.arns@moneymeets.com>"
description: "Set up a specific version of Poetry"
inputs:
  version:
    description: "Poetry version to install"
    required: true
    default: "1.1.5"
runs:
  using: "composite"
  steps:
    - name: Install and configure Poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python - --yes --version=${{ inputs.version }}
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      shell: bash
